Repository My-Epitech-Organisation/Zappynian, pull requests merged in 2025-06, with the labels that each got.

#59 Implement Zappy AI client with connection handling
  ai/Makefile
  ai/src/__init__.py
  ai/src/connection.py
  ai/src/zappy_ai.py
  ai/zappy_ai/client.py
Labels: AI, GOAL

#62 PR(GUI): tiles information details
  gui/Core/EntityManager.cpp
  gui/Core/EntityManager.hpp
  gui/Core/WorldScene.cpp
  gui/Core/WorldScene.hpp
  gui/Entities/AEntity.hpp
  gui/Entities/IEntity.hpp
  gui/Entities/Inventory.cpp
  gui/Entities/Inventory.hpp
  gui/Entities/TileEntity.cpp
  gui/Entities/TileEntity.hpp
  gui/Event/EventReceiver.cpp
  gui/Event/EventReceiver.hpp
  gui/Makefile
Labels: Graphic

#64 PR(GUI): enhance camera movement handling in key input
  gui/Event/EventReceiver.cpp
  gui/Event/EventReceiver.hpp
Labels: Graphic

#82 PR(server): make the server skeleton
  server/Makefile
  server/includes/server.h
  server/src/client_manager.c
  server/src/display_infos.c
  server/src/error_handling.c
  server/src/fill_n_c_f.c
  server/src/fill_p_x_y.c
  server/src/handle_client.c
  server/src/handle_free.c
  server/src/main.c
  server/src/parsing.c
  server/src/set_server.c
  tests/server/test_display_infos.c
  tests/server/test_fill_n_c_f.c
  tests/server/test_fill_p_x_y.c
  tests/server/test_handle_free.c
  tests/server/test_main.c
  tests/server/test_parsing.c
Labels: Server, Network

#91 24 net short action oriented description
  .gitignore
  gui/Makefile
  libzappy_net/Makefile
  libzappy_net/include/zappy_net.h
  libzappy_net/src/zappy_net_client.c
  libzappy_net/src/zappy_net_core.c
  libzappy_net/src/zappy_net_internal.h
  libzappy_net/src/zappy_net_server.c
  libzappy_net/src/zappy_net_socket.c
  tests/zappy_net_lib/Makefile
  tests/zappy_net_lib/run_tests.sh
  tests/zappy_net_lib/test_client_socket.c
  tests/zappy_net_lib/test_edge_cases.c
  tests/zappy_net_lib/test_helpers.c
  tests/zappy_net_lib/test_helpers.h
  tests/zappy_net_lib/test_loopback.c
  tests/zappy_net_lib/test_server_socket.c
  tests/zappy_net_lib/test_socket_close.c
  tests/zappy_net_lib/test_socket_creation.c
Labels: Network

#99 PR(GUI): player level and display information players
  gui/App/Game.cpp
  gui/Core/WorldScene.cpp
  gui/Core/WorldScene.hpp
  gui/Entities/AEntity.hpp
  gui/Entities/IEntity.hpp
  gui/Event/EventReceiver.cpp
  gui/Event/EventReceiver.hpp
Labels: Graphic

#101 PR(GUI): add skybox in the background
  gui/App/Game.cpp
  gui/assets/sky_texture/skydown.png
  gui/assets/sky_texture/skyleft.png
  gui/assets/sky_texture/skymid.png
  gui/assets/sky_texture/skymidleft.png
  gui/assets/sky_texture/skymidright.png
  gui/assets/sky_texture/skyup.png
Labels: Graphic

#107 27 netframers zn readline with partial segment support
  libzappy_net/Makefile
  libzappy_net/include/zappy_net.h
  libzappy_net/src/zappy_net_readline.c
  tests/zappy_net_lib/Makefile
  tests/zappy_net_lib/test_readline_fragmentation.c
Labels: Network

#115 PR(GUI): death of a player
  gui/Core/EntityManager.cpp
  gui/Core/WorldScene.cpp
  gui/Core/WorldScene.hpp
  gui/Event/EventReceiver.cpp
  gui/Event/EventReceiver.hpp
  gui/Network/NetworkClient.hpp
Labels: Graphic

#117 PR(Server) Implementation of the game loop
  server/Makefile
  server/includes/commands.h
  server/includes/death.h
  server/includes/elevation.h
  server/includes/game_loop.h
  server/includes/player.h
  server/includes/resource.h
  server/includes/server.h
  server/includes/team.h
  server/includes/win.h
  server/includes/world.h
  server/src/client_manager.c
  server/src/commands_actions.c
  server/src/commands_communication.c
  server/src/commands_core.c
  server/src/commands_movement.c
  server/src/death.c
  server/src/elevation.c
  server/src/game_loop.c
  server/src/main.c
  server/src/parsing.c
  server/src/player.c
  server/src/resource.c
  server/src/team.c
  server/src/win.c
  server/src/world.c
Labels: Server

#119 PR(lib_network) nethandshake helper for welcome team exchange
  libzappy_net/Makefile
  libzappy_net/include/zappy_net.h
  libzappy_net/src/zappy_net_handshake_client.c
  libzappy_net/src/zappy_net_handshake_server.c
  libzappy_net/src/zappy_net_handshake_utils.c
  libzappy_net/src/zappy_net_internal.h
  tests/zappy_net_lib/Makefile
  tests/zappy_net_lib/test_handshake.c
  tests/zappy_net_lib/test_readline_fragmentation.c
  tests/zappy_net_lib/test_simple_handshake.c
Labels: Network

#121 PR(GUI): broadcast between players
  gui/App/Game.cpp
  gui/Core/EntityManager.cpp
  gui/Core/EntityManager.hpp
  gui/Core/WorldScene.cpp
  gui/Core/WorldScene.hpp
  gui/Network/NetworkClient.hpp
  gui/assets/plane.b3d
  gui/assets/plane_texture/plane_texture.jpg
Labels: Graphic

#125 Fix lzappy net
  .github/workflows/ci.yml
  libzappy_net/Makefile
  libzappy_net/include/zappy_net.h
  libzappy_net/src/zappy_net_handshake_client.c
  libzappy_net/src/zappy_net_server.c
  libzappy_net/src/zappy_net_socket_ops.c
  tests/zappy_net_lib/Makefile
  tests/zappy_net_lib/functional_tests/Makefile
  tests/zappy_net_lib/functional_tests/test_functional_api_extensions.c
  tests/zappy_net_lib/test_api_extensions.c
Labels: Network

#130 Implementation of roles reflexion
  ai/src/command_queue.py
  ai/src/connection.py
  ai/src/inventory_parser.py
  ai/src/roles/miner.py
  ai/src/roles/role_selector.py
  ai/src/roles/scout.py
  ai/src/roles/survivor.py
  ai/src/utils/route_factory.py
  ai/src/vision_parser.py
  ai/src/zappy_ai.py
Labels: AI

#133 PR(DOC) : Add the documentation web doxygen
  Doxyfile
  Makefile
  docs/faq.dox
  docs/getting_started.dox
  docs/mainpage.dox
  docs/user_guide.dox
Labels: DOC

#137 PR(Doc) Pictures into the documentation
  Doxyfile
  docs/images/test.png
  docs/mainpage.dox
Labels: DOC

#147 PR(Server) : Catch commands from the client IA
  server/Makefile
  server/include/server.h
  server/include/team.h
  server/src/catch_commands_from_clients.c
  server/src/client_manager.c
  server/src/commands_core.c
Labels: Server

#149 PR(Server): Add the fork command
  server/Makefile
  server/include/egg.h
  server/include/server.h
  server/include/team.h
  server/src/catch_commands_from_clients.c
  server/src/commands_communication.c
  server/src/commands_core.c
  server/src/egg.c
  server/src/handle_client.c
  server/src/team.c
Labels: Server

#140 PR(GUI): expulsion of players and eggs
  gui/Core/EntityManager.cpp
  gui/Core/EntityManager.hpp
  gui/Core/WorldScene.cpp
  gui/Core/WorldScene.hpp
  gui/Entities/AEntity.hpp
  gui/Entities/Direction.hpp
  gui/Entities/Egg.hpp
  gui/Entities/IEntity.hpp
  gui/Entities/PlayerEntity.hpp
  gui/Event/EventReceiver.cpp
  gui/Network/NetworkClient.hpp
Labels: Graphic

#151 PR(server) : Take object command
  server/Makefile
  server/include/commands.h
  server/include/player.h
  server/include/server.h
  server/include/world.h
  server/src/commands_actions.c
  server/src/commands_core.c
  server/src/inventory_cmd.c
  server/src/world_utils.c
Labels: Server

#156 PR(server) : Death command
  server/src/death.c
Labels: Server

#162 PR(Server) : set object command
  server/include/world.h
  server/src/commands_actions.c
  server/src/world_utils.c
Labels: Server

#158 PR(GUI): death of an egg
  gui/Core/WorldScene.cpp
  gui/Core/WorldScene.hpp
  gui/Network/NetworkClient.hpp
Labels: Graphic

#169 PR: add initial project README and structure overview
  README.md
Labels: DOC

#164 PR(GUI): link network and gui
  Doxyfile
  docs/faq.dox
  docs/getting_started.dox
  docs/mainpage.dox
  docs/user_guide.dox
  gui/App/Game.cpp
  gui/App/Game.hpp
  gui/Core/GameState.cpp
  gui/Core/GameState.hpp
  gui/Core/WorldScene.cpp
  gui/Core/WorldScene.hpp
  gui/Entities/AEntity.hpp
  gui/Entities/TileEntity.hpp
  gui/Makefile
  gui/Network/NetworkClient.cpp
  gui/Network/NetworkClient.hpp
  gui/Network/NetworkManager.cpp
  gui/Network/NetworkManager.hpp
  gui/Network/NetworkManagerImpl.cpp
  gui/Network/NetworkManagerImpl.hpp
  gui/Network/ProtocolParser.cpp
  gui/Network/ProtocolParser.hpp
  gui/src/main.cpp
  libzappy_net/Makefile
  libzappy_net/include/zappy_net_ringbuf.h
Labels: Graphic, Refactor

#176 171 gui accept server command
  gui/App/Game.cpp
  gui/App/Game.hpp
  gui/Core/GameState.cpp
  gui/Core/WorldScene.cpp
  gui/Core/WorldScene.hpp
  gui/Entities/AEntity.hpp
  gui/Entities/PlayerEntity.hpp
  gui/Makefile
  gui/Network/INetworkHandler.hpp
  gui/Network/NetworkClient.cpp
  gui/Network/NetworkClient.hpp
  gui/Network/NetworkManager.cpp
  gui/Network/NetworkManager.hpp
  gui/Network/NetworkManagerImpl.cpp
  gui/Network/NetworkManagerImpl.hpp
  gui/Network/ProtocolParser.cpp
  gui/Network/ProtocolParser.hpp
Labels: Graphic

#178 PR(GUI): add text map
  gui/App/Game.cpp
  gui/App/Game.hpp
  gui/Core/EntityManager.cpp
  gui/Core/EntityManager.hpp
  gui/Core/WorldScene.cpp
  gui/Core/WorldScene.hpp
  gui/Entities/TileEntity.cpp
  gui/Makefile
Labels: Graphic

#186 PR(server) : Resources respawn
  server/include/game_loop.h
  server/include/resource.h
  server/src/game_loop.c
  server/src/resource.c
Labels: Server

#190 PR(AI): Minor update for AI
  ai/src/command_queue.py
  ai/src/inventory_parser.py
  ai/src/roles/breeder.py
  ai/src/roles/leader.py
  ai/src/roles/miner.py
  ai/src/roles/role_selector.py
  ai/src/roles/scout.py
  ai/src/roles/survivor.py
  ai/src/roles/upgrader.py
  ai/src/utils/route_factory.py
  ai/src/zappy_ai.py
Labels: AI

#189 PR(Server) : server limits map handling
  server/include/world.h
  server/src/eject_cmd.c
  server/src/handle_free.c
  server/src/look_vision_tiles.c
  server/src/player.c
  server/src/world.c
  server/src/world_utils.c
Labels: Server

#192 PR(GUI): is edge bug
  gui/App/Game.cpp
  gui/Core/WorldScene.cpp
Labels: Fix, Graphic

#194 feat(EntityManager): enhance stone creation by removing existing item…
  gui/Core/EntityManager.cpp
Labels: Fix, Graphic

#195 PR(GUI): change font color scale
  gui/App/Game.cpp
  gui/App/Game.hpp
  gui/Core/WorldScene.cpp
  gui/Core/WorldScene.hpp
  gui/Event/EventReceiver.cpp
  gui/assets/font/myfont.xml
  gui/assets/font/myfont0.png
Labels: Graphic

#197 40.1 server scheduler manager
  README.md
  docs/gameplay.md
  docs/protocol.md
  libzappy_net/include/zappy_net.h
  libzappy_net/src/zappy_net_io.c
  server/Makefile
  server/include/command_timer.h
  server/include/food_timer.h
  server/include/player.h
  server/include/server.h
  server/include/time_utils.h
  server/include/timing_integration.h
  server/include/timing_manager.h
  server/src/command_timer.c
  server/src/food_timer.c
  server/src/main.c
  server/src/player.c
  server/src/server_loop.c
  server/src/server_player_manager.c
  server/src/server_poll.c
  server/src/time_utils.c
  server/src/timing_integration.c
  server/src/timing_manager.c
  server/src/write_to_client.c
  tests/server/test_broken_pipe.sh
  tests/server/test_pollout_optimization.sh
Labels: Server, Network

#198 83 server core server loop client management core server loop
  ai/src/command_queue.py
  ai/src/connection.py
  ai/src/zappy_ai.py
  libzappy_net/src/zappy_net_handshake_server.c
  libzappy_net/src/zappy_net_io.c
  server/include/commands.h
  server/include/server.h
  server/src/client_handshake_response.c
  server/src/client_manager.c
  server/src/commands_communication.c
  server/src/commands_movement.c
  server/src/inventory_cmd.c
  server/src/look_cmd.c
  server/src/look_current_tile.c
  server/src/look_vision_tiles.c
  server/src/main.c
  server/src/send_gui_egg_info.c
  server/src/send_init_gui.c
  server/src/server_event_handler.c
  server/src/win.c
Labels: Server

#202 PR(AI): Add documentation for ai and improve test for ai
  Doxyfile
  ai/README.md
  docs/ai_devguide.dox
  docs/ai_userguide.dox
  tests/ai/run_tests.py
  tests/ai/test_command_queue.py
  tests/ai/test_connection.py
  tests/ai/test_game_logic.py
  tests/ai/test_incantation_data.py
  tests/ai/test_role_selector.py
  tests/ai/test_roles.py
  tests/ai/test_route_factory.py
  tests/ai/test_utils_route_factory.py
  tests/ai/test_zappy_ai.py
Labels: AI, DOC

#203 192 server fix and check of all the server requirement
  ai/src/command_queue.py
  ai/src/zappy_ai.py
  gui/Network/ProtocolParser.cpp
  server/Makefile
  server/include/commands.h
  server/include/server.h
  server/src/check_elevation.c
  server/src/client_handshake_response.c
  server/src/client_manager.c
  server/src/commands_actions.c
  server/src/commands_movement.c
  server/src/death.c
  server/src/eject_cmd.c
  server/src/look_cmd.c
  server/src/look_current_tile.c
  server/src/send_gui_incantation_info.c
  server/src/server_event_handler.c
  server/src/server_player_manager.c
  server/src/string_utils.c
Labels: Fix, Server

#204 PR(docs): add server user and developer guides to Doxygen configuration
  Doxyfile
  docs/ai_devguide.dox
  docs/ai_userguide.dox
  docs/server_devguide.dox
  docs/server_userguide.dox
Labels: Server, DOC
